!procedure startDfd()
digraph dfd2 {
    rankdir="LR"
    node[shape=record]
    style=filled
    fillcolor=white
!endprocedure

!procedure endDfd()
}
!endprocedure

!procedure External($alias, $label)
    $alias [label="$label" shape=box fillcolor=lightblue style=filled fontcolor=black fontsize=12 color=black width=2];
!endprocedure

!procedure Process($alias, $label)
    $alias [label="0 | $label\n\n" shape=Mrecord fillcolor=white style=filled fontcolor=black fontsize=12 color=black];
!endprocedure

!procedure Flow_R($from, $to, $label = "")
    !if ($label != "")
        $from -> $to [label="$label" dir=forward fontcolor=black fontsize=10 color=black width=1];
    !else
        $from -> $to [dir=forward fontcolor=black fontsize=10 color=black width=1];
    !endif
!endprocedure

!procedure Flow_L($from, $to, $label = "")
    !if ($label != "")
        $from -> $to [label="$label" dir=back fontcolor=black fontsize=10 color=black width=1];
    !else
        $from -> $to [dir=back fontcolor=black fontsize=10 color=black width=1];
    !endif
!endprocedure

!procedure BiFlow($from, $to, $label = "")
    !if ($label != "")
        $from -> $to [label="$label" dir=both fontcolor=black fontsize=10 color=black width=1];
    !else
        $from -> $to [label="$label" dir=both fontcolor=black fontsize=10 color=black width=1];
    !endif
!endprocedure
