' context.puml
' Define a global variable for notation and set a default value
!$notation = "DEFAULT"

' Define a procedure to set the notation
!procedure setNotation(notation)
    !if (notation == "GANE_SARSON" || notation == "YOURDON_DEMARCO" || notation == "SSADM")
        !$notation = notation
    !else
        !$notation = "DEFAULT"
    !endif
!endprocedure

' Define startDfd and endDfd procedures
!procedure startDfd()
digraph dfd2 {
!endprocedure

!procedure endDfd()
}
!endprocedure

!function getTitle($title)
    !return $title
!endfunction

!procedure Title($title)
    graph [rankdir=LR ranksep=1.5 splines=true overlap=false labeljust=c labelloc=t \
    label=<<TABLE BORDER="0" CELLBORDER="0"> \
    <TR><TD><FONT POINT-SIZE="16">$title</FONT></TD></TR> \
    <TR><TD><FONT POINT-SIZE="10">Context Diagram (DFD Level 0)</FONT></TD></TR> \
    <TR><TD><FONT POINT-SIZE="8">$notation Notation</FONT></TD></TR> \
    </TABLE>> ]
!endprocedure

!procedure Process($alias, $label)
    !if ($notation == "GANE_SARSON")
        $alias [label=$label shape=Mrecord fontsize=12 penwidth=2]
    !elseif ($notation == "YOURDON_DEMARCO")
        $alias [label=$label shape=circle fontsize=12 penwidth=2]
    !elseif ($notation == "SSADM")
        $alias [label=$label shape=record fontsize=12 penwidth=2]
    !else
        $alias [label=$label shape=circle fontsize=12 penwidth=2]
    !endif
!endprocedure

!procedure External($alias, $label)
    !if ($notation == "SSADM")
        $alias [label=$label shape=oval fontsize=12 penwidth=2]
    !else
        $alias [label=$label shape=rect fontsize=12 penwidth=2]
    !endif
!endprocedure

' Define the Data Flow macros
!procedure InFlow($alias1, $alias2, $label="")
    !if ($label != "")
        $alias1 -> $alias2 [label=$label fontcolor=black fontsize=10 color=black penwidth=1]
    !else
        $alias1 -> $alias2 [color=black penwidth=1]
    !endif
!endprocedure

!procedure OutFlow($alias1, $alias2, $label="")
    !if ($label != "")
        $alias2 -> $alias1 [label=$label dir=back fontcolor=black fontsize=10 color=black penwidth=1]
    !else
        $alias2 -> $alias1 [dir=back fontcolor=black fontsize=10 color=black penwidth=1]
    !endif
!endprocedure

!procedure BiFlow($alias1, $alias2, $label="")
    !if ($label != "")
        $alias1 -> $alias2 [label=$label dir=both fontcolor=black fontsize=10 color=black penwidth=1]
    !else
        $alias1 -> $alias2 [dir=both fontcolor=black fontsize=10 color=black penwidth=1]
    !endif
!endprocedure
