!$DEFAULT_FILLCOLOR ?= "lightsteelblue1"
!$DEFAULT_STYLE ?= "filled"
!$DEFAULT_FONTCOLOR ?= "#000000"
!$DEFAULT_FONTSIZE ?= 12
!$DEFAULT_BORDERCOLOR ?= "grey"
!$DEFAULT_WIDTH ?= 2
!$DEFAULT_HEIGHT ?= 1
!$DEFAULT_TITLE_FONTSIZE ?= 16
!$DEFAULT_SUBTITLE_FONTSIZE ?= 10
!$DEFAULT_PENWIDTH ?= 1
!$DEFAULT_ARROW_STYLE ?= "solid"
!$DEFAULT_ARROW_COLOR ?= "black"

!$FLOW_FONT_COLOR ?= $DEFAULT_FONTCOLOR
!$FLOW_FONTSIZE ?= 10
!$FLOW_COLOR ?= $DEFAULT_ARROW_COLOR
!$FLOW_PENWIDTH ?= $DEFAULT_PENWIDTH
!$FLOW_ARROW_STYLE ?= $DEFAULT_ARROW_STYLE

!$BIFLOW_FONT_COLOR ?= $DEFAULT_FONTCOLOR
!$BIFLOW_FONTSIZE ?= 10
!$BIFLOW_COLOR = $DEFAULT_ARROW_COLOR
!$BIFLOW_PENWIDTH ?= $DEFAULT_PENWIDTH
!$BIFLOW_ARROW_STYLE ?= $DEFAULT_ARROW_STYLE

!$FLOWBACK_FONT_COLOR ?= $DEFAULT_FONTCOLOR
!$FLOWBACK_FONTSIZE ?= 10
!$FLOWBACK_COLOR = $DEFAULT_ARROW_COLOR
!$FLOWBACK_PENWIDTH ?= $DEFAULT_PENWIDTH
!$FLOWBACK_ARROW_STYLE ?= $DEFAULT_ARROW_STYLE

!procedure Title($title, $LEVEL)
    graph [rankdir=LR ranksep=1.5 labeljust=c labelloc=t \
    label=<<TABLE BORDER="0" CELLBORDER="0"> \
    <TR><TD><FONT POINT-SIZE="$DEFAULT_TITLE_FONTSIZE">$title</FONT></TD></TR> \
    <TR><TD><FONT POINT-SIZE="$DEFAULT_SUBTITLE_FONTSIZE">$LEVEL</FONT></TD></TR> \
    </TABLE>> ]
!endprocedure

!procedure startDfd($label)
digraph dfd2 {
Title($label, $level)
node[shape=record];
!endprocedure

!procedure endDfd()
}
!endprocedure

!unquoted function getLabel($label, $id, $elementType)
  !$formattedLabel = "" 
  !if ($elementType == "process")
    !$formattedLabel = $id + " | " + $label + "\n\n\n"
  !endif
  !if ($elementType == "external")
    !$formattedLabel = $label
  !endif
  !if ($elementType == "datastore")
    !$formattedLabel = "{<f0>" + $id + " |<f1> "+ $label + "}"
  !endif
  !return $formattedLabel
!endfunction

!unquoted procedure Component($alias, $label, $id="", $shape, $fillcolor, $width, $height, $elementType)
    !$formattedLabel = getLabel($label, $id, $elementType)
    $alias [label="$formattedLabel" shape=$shape fillcolor=$fillcolor style=$style fontcolor="$fontcolor" fontsize=$fontsize color=$color width=$width height=$height];
!endprocedure

!unquoted procedure Flow_($from, $to, $label="", $direction="", $style="", $fontcolor="", $fontsize="", $color="", $penwidth="")
  !if ($label != "")
    $from -> $to [label="$label" dir=$direction style="$style" fontcolor="$fontcolor" fontsize=$fontsize color="$color" penwidth=$penwidth ]
  !else
    $from -> $to [dir=$direction style=$style fontcolor=$fontcolor fontsize=$fontsize color=$color penwidth=$penwidth]
  !endif
!endprocedure

!unquoted procedure Flow($from, $to, $label="")
Flow_($from, $to, $label, "forward", $FLOW_ARROW_STYLE, $FLOW_FONTCOLOR, $FLOW_FONTSIZE, $FLOW_COLOR, $FLOW_PENWIDTH)
!endprocedure

!unquoted procedure BiFlow($from, $to, $label="")
Flow_($from, $to, $label, both, $BIFLOW_ARROW_STYLE,  $BIFLOW_FONTCOLOR, $BIFLOW_FONTSIZE, $BIFLOW_COLOR, $FLOW_PENWIDTH)
!endprocedure

!unquoted procedure Flow_Back($from, $to, $label="")
Flow_($from, $to, $label, back, $FLOWBACK_ARROW_STYLE, $FLOWBACK_FONTCOLOR, $FLOWBACK_FONTSIZE, $FLOWBACK_COLOR, $FLOWBACK_PENWIDTH)
!endprocedure

