!include https://raw.githubusercontent.com/ArmanAvanesyan/test/main/DFD.puml

!global $__DFD_LEVEL = 0
!$LEVEL = "Context Diagram (DFD Level 0)"
!global $__DFD_PROCESS_COUNT = 0

!procedure External($alias, $label)
  __Component($alias, $label, "rectangle", $DEFAULT_EXTERNAL_FILLCOLOR)
!endprocedure

!procedure Process($alias, $label)
  !if $__DFD_PROCESS_COUNT > 0
    !error "DFD Level 0 allows only one process"
  !endif
  !$__DFD_PROCESS_COUNT = $__DFD_PROCESS_COUNT + 1

  ' precompute (so we don’t pass an expression as an argument)
  !$pLabel = "0 | " + $label + "\n\n"

  __Component($alias, $pLabel, $DEFAULT_PROCESS_SHAPE, $DEFAULT_PROCESS_FILLCOLOR)
!endprocedure


