' dfd_level1.puml
!include dfd_level0.puml

!procedure TitleLevel1($title)
    graph [label=<<TABLE BORDER="0" CELLBORDER="0"> \
    <TR><TD><FONT POINT-SIZE="16">$title</FONT></TD></TR> \
    <TR><TD><FONT POINT-SIZE="10">Data Flow Diagram Level 1</FONT></TD></TR> \
    </TABLE>> ]
!endprocedure

!procedure DetailedProcess($alias, $label, $number)
    !if ($notation == "GANE_SARSON")
        $alias [label="{<f0> $number |<f1> $label}" shape=Mrecord fontsize=10 penwidth=2]
    !else
        $alias [label="$number.$number\n$label" shape=circle fontsize=10 penwidth=2]
    !endif
!endprocedure

!procedure Connector($alias1, $alias2, $label="", $flowType="forward")
    !if ($flowType == "bi")
        $alias1 -> $alias2 [label="$label" dir=both fontsize=8]
    !elseif ($flowType == "back")
        $alias2 -> $alias1 [label="$label" dir=back fontsize=8]
    !else
        $alias1 -> $alias2 [label="$label" fontsize=8]
    !endif
!endprocedure
