!includeurl https://raw.githubusercontent.com/ArmanAvanesyan/test/main/DFD.puml

!procedure startDfd()
digraph dfd2 {
    node[shape=record];
    subgraph level0 {
!endprocedure

!procedure lvl1()
    }
    subgraph cluster_level1 {
    
!endprocedure

!procedure endDfd()
    }
}
!endprocedure

!procedure startFlows()
}
!endprocedure

' Elements
!procedure External($alias, $label)
    $alias [label="$label", shape=box, fillcolor=$EXTERNAL_FILL_COLOR, style=$ELEMENT_STYLE, fontcolor=$DEFAULT_FONT_COLOR, fontsize=$ELEMENT_FONT_SIZE, color=$DEFAULT_BORDER_COLOR, width=$DEFAULT_BORDER_WIDTH];
!endprocedure

!procedure Process($alias, $id, $name)
    $alias [label="{<f0> $id |<f1> $name\n\n\n}", shape=Mrecord, fillcolor=$PROCESS_FILL_COLOR, style=$ELEMENT_STYLE, fontcolor=$DEFAULT_FONT_COLOR, fontsize=$ELEMENT_FONT_SIZE, color=$DEFAULT_BORDER_COLOR, width=$DEFAULT_BORDER_WIDTH];
!endprocedure

!procedure Store($alias, $id, $name)
    $alias [label="<f0> $id   |<f1> $name", fillcolor=$STORE_FILL_COLOR, style=$ELEMENT_STYLE, fontcolor=$DEFAULT_FONT_COLOR, fontsize=$ELEMENT_FONT_SIZE, color=$DEFAULT_BORDER_COLOR, width=$DEFAULT_BORDER_WIDTH];
!endprocedure
