!includeurl https://raw.githubusercontent.com/ArmanAvanesyan/test/main/DFD.puml

!procedure startDfd()
digraph dfd2 {
    node[shape=record];
    subgraph level0 {
!endprocedure

!procedure lvl1()
    }
    subgraph cluster_level1 {
    
!endprocedure

!procedure endDfd()
    }
}
!endprocedure

!procedure startFlows()
}
!endprocedure

!function getTitle($title)
    !return $title
!endfunction

!unquoted procedure Title($title)
    graph [rankdir=LR ranksep=1.5 splines=true overlap=false labeljust=c labelloc=t fontname="Helvetica,Arial,sans-serif"\
    label=<<TABLE BORDER="0" CELLBORDER="0"> \
    <TR><TD><FONT COLOR="#345000" POINT-SIZE="16">$title</FONT></TD></TR> \
    <TR><TD><FONT COLOR="#000000" POINT-SIZE="10">DFD Level 1</FONT></TD></TR> \
    </TABLE>> ]
!endprocedure

' Elements
!procedure External($alias, $label)
    $alias [label="$label", shape=box fillcolor=lightblue style=filled fontcolor="#000000"  fontsize=12 color=blue width=2];
!endprocedure

!procedure Process($alias, $id, $name)
    $alias [label="{<f0> $id |<f1> $name\n\n\n}" fillcolor=white fontcolor="#000000" fontsize=12 color=blue width=2];
!endprocedure

!procedure Store($alias, $id, $name)
    $alias [label="<f0> $id   |<f1> $name" fillcolor=white style=filled fontcolor="#000000" fontsize=12 color=blue width=2];
!endprocedure
