!procedure startDfd($title)
digraph dfd2 {
rankdir="LR"
node[shape=record]
!endprocedure

!procedure endDfd()
}
!endprocedure

!procedure External($alias, $label)
    $alias [label="$label" shape=box fillcolor=lightblue style=filled width=2];
!endprocedure

!procedure Process($alias, $id, $name)
    $alias [label="{<f0> $id |<f1> $name\n\n\n}" shape=Mrecord style=bold];
!endprocedure

!procedure Store($alias, $id, $name)
    $alias [label="<f0> $id   |<f1> $name" fillcolor=lightblue style=filled];
!endprocedure

!procedure Flow($from, $to, $label = "")
    !if ($label != "")
         $from -> $to [ label="$label"];
    !else
         $from -> $to [ constraint=false];
    !endif
!endprocedure

!procedure ExtToProc($ext, $proc, $label = "")
    Flow($ext, $proc, $label);
!endprocedure

!procedure ProcToExt($proc, $ext, $label = "")
    Flow($proc, $ext, $label);
!endprocedure

!procedure ProcToProc($proc1, $proc2, $label = "")
    Flow($proc1, $proc2, $label);
!endprocedure

!procedure ProcToStore($proc, $store, $label = "")
    Flow($proc, $store, $label);
!endprocedure

!procedure StoreToProc($store, $proc, $label = "")
    Flow($store, $proc, $label);
!endprocedure

!procedure startProcessCluster()
subgraph cluster_processes {
    label="Processes";
    rankdir=TB;
!endprocedure

!procedure endProcessCluster()
}
!endprocedure

!procedure startStoreCluster()
subgraph cluster_stores {
    label="Data Stores";
    rankdir=TB;
!endprocedure

!procedure endStoreCluster()
}
!endprocedure
