!includeurl https://raw.githubusercontent.com/ArmanAvanesyan/test/main/DFD.puml
!$level="Context Diagram (DFD Level 0)"

!$EXTERNAL_SHAPE = "box"
!$EXTERNAL_FILLCOLOR = "lightsteelblue1"
!$EXTERNAL_WIDTH = 1
!$EXTERNAL_HEIGHT = 2

!$PROCESS_SHAPE = "Mrecord"
!$PROCESS_FILLCOLOR = "lightsteelblue1"
!$PROCESS_WIDTH = 2
!$PROCESS_ HEIGHT = 1

!$DEFAULT_STYLE = "filled"
!$DEFAULT_FONTCOLOR = "#000000"
!$DEFAULT_FONTSIZE = 12
!$DEFAULT_BORDERCOLOR = "grey"

!unquoted procedure External($alias, $label)
    $alias [label="$label" shape=$EXTERNAL_SHAPE fillcolor=$EXTERNAL_FILLCOLOR style=$DEFAULT_STYLE fontcolor="$DEFAULT_FONTCOLOR"  fontsize=$DEFAULT_FONTSIZE color=$DEFAULT_BORDERCOLOR width=$EXTERNAL_WIDTH height=$EXTERNAL_HEIGHT];
!endprocedure

!unquoted procedure Process($alias, $label)
   $alias [label="0 | $label\n\n" shape=$PROCESS_SHAPE fillcolor=$PROCESS_FILLCOLOR style=$DEFAULT_STYLE fontcolor="$DEFAULT_FONTCOLOR" fontsize=$DEFAULT_FONTSIZE color=$DEFAULT_BORDERCOLOR width=$PROCESS_WIDTH];
!endprocedure
