!includeurl https://raw.githubusercontent.com/ArmanAvanesyan/test/main/DFD.puml

' Base Element Functions
!unquoted function $formatLabel($shape, $label)
  !$formattedLabel = ""

  !if ($shape == "Mrecord")
    !$formattedLabel = '0 | ' + $label + ' \n\n'
  !else
    !$formattedLabel = $label
  !endif

  !return $formattedLabel
!endfunction

!unquoted function $getElementLine($shape, $alias, $label)
  !$formattedLabel = $formatLabel($shape, $label)
 !$line = $alias [label=" $formattedLabel ", shape=$shape]
  !return $line
!endfunction

' Start & End of DFD

!procedure startDfd()
digraph dfd2 {
    rankdir="LR"
    node[shape=record]
!endprocedure

!procedure endDfd()
}
!endprocedure

' Element Constructors

' External Entity Constructor
!unquoted procedure External($alias, $label)
  $getElementLine(box, $alias, $label)
!endprocedure

' Process Constructor
!unquoted procedure Process($alias, $label)
  $getElementLine(Mrecord, $alias, $label)
!endprocedure

@enduml
