!includeurl https://raw.githubusercontent.com/ArmanAvanesyan/test/main/DFD.puml

' Base Element Function
!function $getBaseElement($shape, $allias, $id, $label)
  !$element = ""
  
 !if ($shape == "Mrecord")
    !$element = "0 | " + $label + "\n\n"
  !else
    !$element = $label
  !endif

  !return $element
!endfunction

!function $getElementLine($shape, $elementType, $alias, $label)
  !$baseProp = $getBaseElement($shape, $alias, "", $label)
  !$line = $alias + " [label=" + %chr(34) + $baseProp + %chr(34) + ", shape=" + $shape + "]"
  !return $line
!endfunction

' Start & End of DFD

!procedure startDfd()
digraph dfd2 {
    rankdir="LR"
    node[shape=record]
!endprocedure

!procedure endDfd()
}
!endprocedure

' Element Constructors

' External Entity Constructor
!unquoted procedure External($alias, $label)
  $getElementLine("box", "External", $alias, $label)
!endprocedure

' Process Constructor
!unquoted procedure Process($alias, $label)
  $getElementLine("Mrecord", "Process", $alias, $label)
!endprocedure

@enduml
