' Colors
' ##################################

!define ELEMENT_FONT_COLOR #FFFFFF
!define PROCESS_BG_COLOR #08427B

' Styling
' ##################################

!global $TECHN_FONT_SIZE = 12

skinparam defaultTextAlignment center
skinparam wrapWidth 200
skinparam maxMessageSize 150

skinparam rectangle {
    StereotypeFontSize 12
    shadowing false
}

skinparam Arrow {
    Color #666666
    FontColor #666666
    FontSize 12
}

' Rectangle styling for processes
skinparam rectangle<<process>> {
    StereotypeFontColor ELEMENT_FONT_COLOR
    FontColor ELEMENT_FONT_COLOR
    BackgroundColor PROCESS_BG_COLOR
    BorderColor #073B6F
}

' Elements
' ##################################

!function $getProcess($id, $name)
!if ($id == "")
!return '<$process>\n=='+$name
!endif
!if ($id != "")
!return '<$process>\n=='+$id+'\n\n'+$name
!endif
!endfunction

!unquoted procedure Process($alias, $name, $id="")
rectangle "$getProcess($id, $name)" <<process>> as $alias
!endprocedure
