!$DEFAULT_ARROW_FONTSIZE ?= 10
!$DEFAULT_ARROW_FONTCOLOR ?= "black"
!$DEFAULT_PENWIDTH ?= 1
!$DEFAULT_ARROW_STYLE ?= "solid"
!$DEFAULT_ARROW_COLOR ?= "black"

!procedure Title($title, $level)
    graph [rankdir=LR ranksep=1.5 labeljust=c labelloc=t \
    label=<<TABLE BORDER="0" CELLBORDER="0"> \
    <TR><TD><FONT POINT-SIZE="16">$title</FONT></TD></TR> \
    <TR><TD><FONT POINT-SIZE="10">$level</FONT></TD></TR> \
    </TABLE>> ]
!endprocedure

!procedure startDfd($label)
digraph dfd2 {
Title($label, $level)
node[shape=record];
!endprocedure

!procedure endDfd()
}
!endprocedure

!unquoted procedure Component($alias, $label, $shape="", $fiillcolor="", $style="", $fontcolor="", $fontsize="", $bordercolor="", $width="", $height="")
    $alias [label="$label" shape=$shape fillcolor=$fillcolor style=$style fontcolor="$fontcolor" fontsize=$fontsize color=$bordercolor width=$width height=$height];
!endprocedure

!unquoted procedure Flow_($from, $to, $label="", $direction="")
  !if ($label != "")
    $from -> $to [label="$label" dir=$direction]
  !else
    $from -> $to [dir=$direction]
  !endif
!endprocedure

!unquoted procedure Flow($from, $to, $label="")
Flow_($from, $to, $label, forward)
!endprocedure

!unquoted procedure BiFlow($from, $to, $label="")
Flow_($from, $to, $label, both)
!endprocedure

!unquoted procedure Flow_Back($from, $to, $label="")
Flow_($from, $to, $label, back)
!endprocedure
!unquoted procedure Flow_($from, $to, $label="", $direction="")
  $from -> $to [label="$label" dir=$direction style=$DEFAULT_ARROW_STYLE fontcolor=$DEFAULT_ARROW_FONTCOLOR fontsize=$DEFAULT_ARROW_FONTSIZE color=$DEFAULT_ARROW_COLOR penwidth=$FLOW_PENWIDTH]
!endprocedure

!unquoted procedure Flow($from, $to, $label="")
    Flow_($from, $to, $label, forward)
!endprocedure

!unquoted procedure BiFlow($from, $to, $label="")
    Flow_($from, $to, $label, both)
!endprocedure

!unquoted procedure Flow_Back($from, $to, $label="")
    Flow_($from, $to, $label, back)
!endprocedure

' Layout Helpers

!unquoted procedure Lay_D($from, $to)
{
  newrank=true;
  $from -> $to [style=invis, constraint=true];
}
!endprocedure

!unquoted procedure Lay_U($from, $to)
  {newrank=true; $to -> $from [style=invis, constraint=true]}
!endprocedure

!unquoted procedure Lay_R($from, $to)
  {{ rank=same; $from -> $to [style=invis, constraint=true]}}
!endprocedure

!unquoted procedure Lay_L($from, $to)
  {{rank=same; $to -> $from [style=invis, constraint=true]}}
!endprocedure
